# Generated by Django 4.0.3 on 2023-04-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptOrDecline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'accept_or_decline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(db_column='Admin_id', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=12)),
                ('verified_driver', models.IntegerField(blank=True, db_column='verified_Driver', null=True)),
            ],
            options={
                'db_table': 'Admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer_id', primary_key=True, serialize=False)),
                ('pass_word', models.CharField(db_column='Pass_word', max_length=128)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=12)),
                ('dob', models.DateField(db_column='DOB')),
                ('notifications', models.CharField(blank=True, max_length=200, null=True)),
                ('current_location_lat', models.FloatField(blank=True, null=True)),
                ('current_location_long', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('pass_word', models.CharField(db_column='Pass_word', max_length=128)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=12)),
                ('dob', models.DateField(db_column='DOB')),
                ('verified', models.IntegerField(blank=True, default=0, null=True)),
                ('notifications', models.CharField(blank=True, max_length=200, null=True)),
                ('current_location_lat', models.FloatField(blank=True, null=True)),
                ('current_location_long', models.FloatField(blank=True, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('complaints', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=100)),
                ('drop_location', models.CharField(max_length=100)),
                ('payable_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('pickup_time', models.TimeField()),
                ('drop_time', models.TimeField()),
                ('date_of_trip', models.DateField()),
                ('mode_of_transaction', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_firstname', models.CharField(max_length=100)),
                ('owner_middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_lastname', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=100)),
                ('date_of_manufacture', models.DateField()),
                ('validity', models.DateField()),
                ('car_model', models.CharField(max_length=100)),
                ('car_make', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hatchback',
            fields=[
                ('tot_passengers', models.IntegerField(blank=True, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.vehicle')),
            ],
            options={
                'db_table': 'HATCHBACK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sedan',
            fields=[
                ('comfort_level', models.IntegerField(blank=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.vehicle')),
            ],
            options={
                'db_table': 'SEDAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suv',
            fields=[
                ('roadtype', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.vehicle')),
            ],
            options={
                'db_table': 'SUV',
                'managed': False,
            },
        ),
    ]
